# set the basic image 
FROM python:3.8-slim

# add all files in current folder
ADD . /dave

# set working directory
WORKDIR /dave

# install necessary packages
RUN apt-get update && apt-get install -y git
RUN pip install -U pip
RUN pip install -r requirements.txt

# Clean up
RUN apt-get clean && pip cache purge && rm -rf .git/

# run uvicorn to connect to dave via api 
CMD ["uvicorn", "dave.dave.api:app", "--host", "0.0.0.0", "--port", "80"]




