# set the basic image 
FROM python:3.8-slim

# add all files in current folder
ADD . /dave

# set working directory
WORKDIR /dave

# install necessary packages
RUN pip install uvicorn

# run uvicorn to connect to dave via api 
CMD ["uvicorn", "dave.dave.api:app", "--host", "0.0.0.0", "--port", "80"]
